default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: password
  host: db

development:
  <<: *default
  database: mydb

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>

